title: Tracking of parcels for Poland Post
author: Eugene Zuev
theme: jekyll-theme-cayman
branch: "gh-pages" #  use "master" for user page or "gh-pages" for project pages
exclude:
  - .gitignore
paginate_path: "/about/page:num/"