title: My Website
author: Eugene Zuev
theme: jekyll-theme-cayman
exclude:
  - .idea/
  - .gitignore
  - src
  - .github
# these are the files and directories that jekyll will exclude from the build
include:
  - readme.md
  - LICENSE
permalink: /readme/