name: Deploy app to AWS ECR

on:
  pull_request:
    branches:
      - main
  push:	
    paths:
      - '.github/workflows/aws-deploy.yml'
      - 'src/scss/**'
      - 'src/app/**'
      - 'src/design/img/**'
      - '.dockerignore'
      - 'Dockerfile'
      - 'heroku.yml'
      - 'package.json'
      - 'requirements.txt'
    branches:	
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest   
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: emonitoring-poczta-polska
        IMAGE_TAG: latest
        GITHUB_TOCKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOCKEN
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
        docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache:$IMAGE_TAG --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache .
        docker tag $IMAGE_TAG docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/build-cache || true
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG