name: Deploy app to Heroku

on:
  push:	
    paths:
      - 'src/scss/**'
      - 'src/app/**'
      - 'src/design/img/**'
      - '.dockerignore'
      - 'Dockerfile'
      - 'heroku.yml'
      - 'package.json'
      - 'requirements.txt'
    branches:	
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "emonitoring-poczta-polska"
          heroku_email: "zhekazuev@gmail.com"
          usedocker: true
