name: Deploy app to Heroku

on:
  push:	
    paths:
      - 'src/scss/**'
      - 'src/app/**'
      - 'src/design/img/**'
      - 'package.json'
      - 'Dockerfile'
      - '.dockerignore'
      - 'heroku.yml'
      - 'requirements.txt'
    branches:	
      - main

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker build . # will run buildx

    # Deploy to Heroku
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "emonitoring-poczta-polska"
            heroku_email: "zhekazuev@gmail.com"
