name: Deploy app to Heroku

on:
  push:	
    paths:
      - 'src/scss/**'
      - 'src/app/**'
      - 'src/design/img/**'
      - '.dockerignore'
      - 'Dockerfile'
      - 'heroku.yml'
      - 'package.json'
      - 'requirements.txt'
    branches:	
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: "zhekazuev@gmail.com"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "emonitoring-poczta-polska"
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
